# Generated by Django 4.0.4 on 2022-04-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0004_tag_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
