# Generated by Django 4.0.5 on 2022-06-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0006_custumer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
