# Generated by Django 4.0.5 on 2022-06-14 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Setoran', '0008_alter_custumer_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Ustadz',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='custumer',
            new_name='ustadz',
        ),
    ]
