# Generated by Django 4.0.5 on 2022-06-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0010_mahasantri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awalan', models.CharField(blank=True, max_length=200, null=True)),
                ('halaman', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=200, null=True)),
                ('fasol', models.CharField(blank=True, choices=[('furudil_udui', 'furudil udui'), ('tayamum', 'tayamun')], max_length=200, null=True)),
                ('bab', models.CharField(blank=True, choices=[('Sholat', 'Sholat'), ('Zakat', 'Zakat')], max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mahasantri',
            name='user',
        ),
        migrations.AlterField(
            model_name='mahasantri',
            name='jk',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mahasantri',
            name='status',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Setoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('nilai', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=200, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('mahasantri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Setoran.mahasantri')),
                ('setoran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Setoran.kitab')),
            ],
        ),
    ]
