# Generated by Django 4.0.5 on 2022-06-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0012_rename_setoran_setoran_kitab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setoran',
            name='kitab',
        ),
        migrations.DeleteModel(
            name='Kitab',
        ),
    ]
