# Generated by Django 4.0.5 on 2022-06-16 10:46

import Setoran.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0014_kitab_setoran_kitab'),
    ]

    operations = [
        migrations.AddField(
            model_name='setoran',
            name='checkbox',
            field=models.BooleanField(default=False, verbose_name=Setoran.models.Kitab),
        ),
    ]
