# Generated by Django 4.0.5 on 2022-06-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0015_setoran_checkbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setoran',
            name='checkbox',
            field=models.BooleanField(),
        ),
    ]
