# Generated by Django 4.0.5 on 2022-06-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0017_remove_setoran_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='setoran',
            name='nilai',
        ),
        migrations.RemoveField(
            model_name='setoran',
            name='note',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
