# Generated by Django 4.0.5 on 2022-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0018_remove_product_tag_remove_setoran_nilai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setoran',
            name='nilai',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='setoran',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
