# Generated by Django 4.0.5 on 2022-08-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0022_setoran_ketengan_setoran_nilai_alter_kitab_bab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustadz',
            name='profile_pic',
        ),
    ]
