# Generated by Django 4.0.5 on 2022-08-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0023_remove_ustadz_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setoran',
            old_name='ketengan',
            new_name='catatan',
        ),
        migrations.AddField(
            model_name='setoran',
            name='lulus',
            field=models.BooleanField(default=False),
        ),
    ]
