# Generated by Django 4.0.5 on 2022-08-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0024_rename_ketengan_setoran_catatan_setoran_lulus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setoran',
            name='lulus',
            field=models.BooleanField(),
        ),
    ]
