# Generated by Django 4.0.5 on 2022-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0025_alter_setoran_lulus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('count', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
