# Generated by Django 4.0.5 on 2022-09-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0026_chart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setoran',
            unique_together={('mahasantri', 'kitab')},
        ),
    ]
