# Generated by Django 4.0.5 on 2022-09-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0028_alter_setoran_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setoran',
            unique_together=set(),
        ),
    ]
