# Generated by Django 4.0.5 on 2022-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0029_alter_setoran_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='setoran',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='setoran',
            name='date_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
