# Generated by Django 4.0.5 on 2022-09-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0030_setoran_time_created_alter_setoran_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setoran',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
