# Generated by Django 4.0.5 on 2022-09-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0031_alter_setoran_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setoran',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='setoran',
            name='time_created',
        ),
    ]
