# Generated by Django 4.0.5 on 2022-09-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0032_remove_setoran_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setoran',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='setoran',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
