# Generated by Django 4.0.5 on 2022-09-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0033_setoran_date_created_setoran_time_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
