# Generated by Django 4.0.5 on 2022-09-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setoran', '0034_delete_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setoran',
            name='lulus',
            field=models.BooleanField(default=False),
        ),
    ]
